spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
server:
  port: 9096